# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'des.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(394, 300)
        Form.setMinimumSize(QtCore.QSize(394, 300))
        Form.setMaximumSize(QtCore.QSize(394, 300))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(82, 81, 81))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 52, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 87, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(43, 124, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(82, 81, 81))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 52, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 87, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(43, 124, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(82, 81, 81))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 87, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 87, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 145, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        Form.setPalette(palette)
        Form.setMouseTracking(False)
        Form.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Form.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Pictures/EV@.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(189, -1, 16, 301))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.sendBtn = QtWidgets.QPushButton(Form)
        self.sendBtn.setGeometry(QtCore.QRect(-10, 250, 208, 51))
        self.sendBtn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.sendBtn.setObjectName("sendBtn")
        self.getBtn = QtWidgets.QPushButton(Form)
        self.getBtn.setGeometry(QtCore.QRect(197, 250, 211, 51))
        self.getBtn.setObjectName("getBtn")
        self.pkgBox = QtWidgets.QLineEdit(Form)
        self.pkgBox.setGeometry(QtCore.QRect(201, 10, 192, 25))
        self.pkgBox.setObjectName("pkgBox")
        self.pkBtn = QtWidgets.QPushButton(Form)
        self.pkBtn.setGeometry(QtCore.QRect(201, 40, 191, 25))
        self.pkBtn.setObjectName("pkBtn")
        self.pathToFile = QtWidgets.QLabel(Form)
        self.pathToFile.setGeometry(QtCore.QRect(10, 180, 191, 17))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(136, 138, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 138, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 138, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pathToFile.setPalette(palette)
        self.pathToFile.setObjectName("pathToFile")
        self.cpBtn = QtWidgets.QPushButton(Form)
        self.cpBtn.setGeometry(QtCore.QRect(10, 200, 80, 25))
        self.cpBtn.setObjectName("cpBtn")
        self.pksBox = QtWidgets.QLineEdit(Form)
        self.pksBox.setGeometry(QtCore.QRect(2, 10, 191, 25))
        self.pksBox.setObjectName("pksBox")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 40, 101, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(200, 80, 191, 81))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 181, 101))
        self.label_3.setObjectName("label_3")
        self.dftBtn = QtWidgets.QPushButton(Form)
        self.dftBtn.setGeometry(QtCore.QRect(200, 200, 80, 25))
        self.dftBtn.setObjectName("dftBtn")
        self.pathToFile_2 = QtWidgets.QLabel(Form)
        self.pathToFile_2.setGeometry(QtCore.QRect(200, 180, 191, 17))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(136, 138, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 138, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 138, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pathToFile_2.setPalette(palette)
        self.pathToFile_2.setObjectName("pathToFile_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "EVA-8"))
        self.sendBtn.setText(_translate("Form", "Encode"))
        self.getBtn.setText(_translate("Form", "Decode"))
        self.pkBtn.setText(_translate("Form", "Generate Public Key"))
        self.pathToFile.setText(_translate("Form", "Choose path to file"))
        self.cpBtn.setText(_translate("Form", "Choose..."))
        self.label.setText(_translate("Form", "Enter Public Key"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p>Choose path to encode file </p><p>(example: image.txt)</p><p>Push to &quot;Decode button&quot;</p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p>Choose path to file for encoding</p><p>Push on &quot;Encode&quot; button</p><p>You can find encode-file</p><p>in folder eFiles</p></body></html>"))
        self.dftBtn.setText(_translate("Form", "Choose..."))
        self.pathToFile_2.setText(_translate("Form", "Choose path to file"))
